# Generated by Django 5.2.5 on 2025-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_success_markdown',
            field=models.TextField(blank=True, help_text='Optional markdown shown to users after a successful registration.', null=True),
        ),
    ]
