# Generated by Django 5.2.5 on 2025-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_registration_success_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancellation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
