# Generated by Django 5.2.5 on 2025-10-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemaillog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventemaillog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventemaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
