# Generated by Django 5.2.5 on 2025-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventemaillog_deleted_at_eventemaillog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemaillog',
            name='kind',
            field=models.CharField(choices=[('invite_non_registered', 'Invite non-registered users'), ('send_skyroom_credentials', 'send skyroom credentials'), ('send_event_announcement', 'send_event_announcement'), ('send_event_announcement2', 'send_event_announcement2'), ('send_event_announcement3', 'send_event_announcement3')], max_length=64),
        ),
    ]
