# Generated by Django 4.2.13 on 2025-11-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('events', '0008_alter_eventemaillog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='payments.discountcode'),
        ),
        migrations.AddField(
            model_name='registration',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
