# Generated by Django 5.2.5 on 2025-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_backfill_registration_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemaillog',
            name='context_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventemaillog',
            unique_together={('event', 'user', 'kind', 'context_hash')},
        ),
    ]
