# Generated by Django 4.2.13 on 2025-11-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventemaillog_context_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemaillog',
            name='kind',
            field=models.CharField(choices=[('invite_non_registered', 'Invite non-registered users'), ('send_skyroom_credentials', 'Skyroom credentials'), ('send_event_announcement', 'Event announcement'), ('send_event_announcement2', 'Event announcement 2'), ('send_event_announcement3', 'Event announcement 3')], max_length=64),
        ),
    ]
